project: 
  type: website
  output-dir: docs

website:
  title: "Antonio Flores - Data Analysis Portfolio"
  navbar:
    left:
      - text: "About Me"
        file: aboutme.qmd
      - text: "Projects"
        menu:
          - text: "Financial Data Classification Prediction Project"
            file: classification-prediction-project/manuscript/Manuscript_Copy.qmd
          - text: "Housing Prices Regression Prediction Project"
            file: regression-prediction-project/regression-prediction-project.qmd
          - text: "Basketball Data Visualization Project"
            file: data-visualization-project/data-visualization-project.qmd
          - text: "Data Analysis of Public Education Funding"
            file: "data-analysis-public-eduction-funding/data-analysis-public-education-funding.qmd"
          - text: "Market Segmentation Project"
            file: "market-segmentation-project/market-segmentation-project.qmd"
          - text: "Python Data Annotation Project"
            file: "python-annotation-project/python-annotation-project.qmd"
      - text: "Exercises"
        menu:
          - text: "R Coding Exercise"
            file: coding-exercise/coding-exercise.qmd
          - text: "Presentation Exercise"
            file: presentation-exercise/presentation-exercise.qmd
          - text: "Tidy Tuesday Exercise"
            file: tidytuesday-exercise/tidytuesday-exercise.qmd
          - text: "Synthetic Data Exercise"
            file: synthetic-data-exercise/Synthetic_Data.qmd
          - text: "Data Analysis Exercise"
            file: cdcdata-exercise/code/cdcdata-exercise.qmd
    right:
      - icon: github 
        href: https://github.com/anotherantonioflores/antonioflores-P2-portfolio

format:
  html:
    theme: lux
    highlight: zenburn
    css: styles.css
    toc: FALSE


